spring:
  datasource:
    url: jdbc:h2:mem:employeeAppraisals;MODE=PostgreSQL
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:11001/eureka
logging:
  level:
    org:
      hibernate:
        type: trace