spring:
  profiles:
    active: default,swagger-ui,oauth2,local-postgresql
  application:
    name: employeeAppraisals-v1
  jackson:
    serialization:
      write_dates_as_timestamps: false
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: validate
server:
  port: 11004
flyway:
  locations: db/migration/{vendor}
logging:
  level:
    com:
      gft: TRACE
      netflix:
        discovery: ERROR
        eureka: ERROR
com:
  gft:
    businessRules:
      maxMenteeReferences: 5
