spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/employeeappraisals
    platform: postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
management:
  security:
    enabled: false
security:
  basic:
    enabled: false
logging:
  level:
    com:
      gft: TRACE
      netflix:
        discovery: ERROR
        eureka: ERROR
eureka:
  instance:
    ipAddress: 10.200.202.122
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://10.200.202.122:11001/eureka
