spring:
  datasource:
    url: jdbc:postgresql://10.200.220.130:5432/employeeappraisals
    platform: postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
management:
  security:
    enabled: false
security:
  basic:
    enabled: false
eureka:
  instance:
    ipAddress: 10.200.220.130
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://10.200.220.130:11001/eureka
