spring:
  datasource:
    url: jdbc:postgresql://10.200.220.130:11025/employeeappraisals
    platform: postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
eureka:
  instance:
    ipAddress: 10.200.220.130
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://10.200.220.130:11021/eureka
server:
  port: 11024
