spring:
  profiles:
    active: default,dev,oauth2,local
  application:
    name: employeeAppraisals-v1
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: validate
server:
  port: 11004
logging:
  level:
    com:
      gft: TRACE
      netflix:
        discovery: ERROR
        eureka: ERROR
